# Generated by Django 5.2.7 on 2025-10-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email',models.EmailField()),
                ('password', models.CharField(max_length=100,default="farmer12345")),
                ('farm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'farmer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.farmer')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date'],
            },
        ),
    ]
