# Generated by Django 5.2.7 on 2025-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='contract_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('contract', 'Contract')], default='casual', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
