# Generated by Django 5.2.7 on 2025-10-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_farmer_contract_type_farmer_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendance_attendance',
        ),
    ]
